$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Markdown Print Viewer v1.0.0 - Offline single-file builder
# Downloads pinned open-source dependencies once and embeds both code and
# license texts into offline/index.html. The generated file requires no
# runtime network connection.

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$templatePath = Join-Path $here 'index.template.html'
$outputPath = Join-Path $here 'index.html'
$marker = '<!--__OFFLINE_LIBRARIES__-->'

if (-not (Test-Path -LiteralPath $templatePath)) {
    throw "Template not found: $templatePath"
}

try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
} catch {}

$dependencies = @(
    [pscustomobject]@{
        Name = 'markdown-it 15.0.1'
        Url = 'https://cdn.jsdelivr.net/npm/markdown-it@15.0.1/dist/browser/markdown-it.umd.min.js'
        License = 'MIT'
        LicenseUrls = @('https://cdn.jsdelivr.net/npm/markdown-it@15.0.1/LICENSE')
    },
    [pscustomobject]@{
        Name = 'markdown-it-task-lists 2.1.1'
        Url = 'https://cdn.jsdelivr.net/npm/markdown-it-task-lists@2.1.1/dist/markdown-it-task-lists.min.js'
        License = 'MIT'
        LicenseUrls = @('https://cdn.jsdelivr.net/npm/markdown-it-task-lists@2.1.1/LICENSE')
    },
    [pscustomobject]@{
        Name = 'markdown-it-footnote 4.0.0'
        Url = 'https://cdn.jsdelivr.net/npm/markdown-it-footnote@4.0.0/dist/markdown-it-footnote.min.js'
        License = 'MIT'
        LicenseUrls = @('https://cdn.jsdelivr.net/npm/markdown-it-footnote@4.0.0/LICENSE')
    },
    [pscustomobject]@{
        Name = 'DOMPurify 3.4.14'
        Url = 'https://cdn.jsdelivr.net/npm/dompurify@3.4.14/dist/purify.min.js'
        License = 'Apache-2.0 OR MPL-2.0'
        LicenseUrls = @(
            'https://cdn.jsdelivr.net/npm/dompurify@3.4.14/LICENSE',
            'https://cdn.jsdelivr.net/npm/dompurify@3.4.14/LICENSE-MPL'
        )
    }
)

function Get-RemoteText([string] $Uri) {
    $response = Invoke-WebRequest -Uri $Uri -UseBasicParsing -ErrorAction Stop
    $text = [string]$response.Content
    if ([string]::IsNullOrWhiteSpace($text)) { throw "Empty response: $Uri" }
    return $text
}

function Escape-ScriptEnd([string] $Text) {
    return ($Text -replace '(?i)</script', '<\/script')
}

$template = [IO.File]::ReadAllText($templatePath, [Text.Encoding]::UTF8)
if (-not $template.Contains($marker)) { throw 'Offline library marker not found in template.' }

$blocks = New-Object System.Collections.Generic.List[string]
$licenseSections = New-Object System.Collections.Generic.List[string]
$blocks.Add('  <!-- Vendored dependencies: generated by offline/build_offline.ps1. No runtime network access is required. -->')

foreach ($dep in $dependencies) {
    Write-Host ("Downloading {0} ..." -f $dep.Name)
    $code = Get-RemoteText $dep.Url
    if ($code.Length -lt 100) { throw ("Downloaded content for {0} looks invalid." -f $dep.Name) }
    $code = Escape-ScriptEnd $code

    $blocks.Add(("  <!-- {0} | {1} | source: {2} -->" -f $dep.Name, $dep.License, $dep.Url))
    $blocks.Add('  <script>')
    $blocks.Add($code)
    $blocks.Add('  </script>')

    foreach ($licenseUrl in $dep.LicenseUrls) {
        Write-Host ("  license: {0}" -f $licenseUrl)
        $licenseText = Get-RemoteText $licenseUrl
        $licenseSections.Add(("===== {0} | {1} =====`r`nSource: {2}`r`n`r`n{3}" -f $dep.Name, $dep.License, $licenseUrl, $licenseText))
    }
}

$blocks.Add('  <script type="text/plain" id="third-party-licenses">')
$blocks.Add((Escape-ScriptEnd ([string]::Join("`r`n`r`n", $licenseSections))))
$blocks.Add('  </script>')

$embedded = [string]::Join([Environment]::NewLine, $blocks)
$output = $template.Replace($marker, $embedded)

if ($output -match '<script\s+[^>]*src\s*=') {
    throw 'Build validation failed: an external script reference remains.'
}
if ($output.Contains($marker)) {
    throw 'Build validation failed: offline marker remains.'
}

$utf8NoBom = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outputPath, $output, $utf8NoBom)

$info = Get-Item -LiteralPath $outputPath
Write-Host ''
Write-Host 'Offline edition generated successfully.' -ForegroundColor Green
Write-Host ("Output: {0}" -f $info.FullName)
Write-Host ("Size:   {0:N0} bytes" -f $info.Length)
Write-Host ''
Write-Host 'offline/index.html is now self-contained and requires no runtime network connection.'
